apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: public-issuer
  namespace: cert-manager
spec:
  acme:
    email: acm-cicd@redhat.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: haproxy
      selector:
        matchLabels:
          use-http01-solver: "true"
    - dns01:
        cnameStrategy: Follow
        route53:
          accessKeyID: NOT_MY_ACCESS_KEY
          region: us-east-1
          secretAccessKeySecretRef:
            key: aws_secret_access_key
            name: aws-creds
      selector:
        matchLabels:
          use-dns01-solver: "true"