apiVersion: hive.openshift.io/v1
kind: ClusterPool
metadata:
  name: canary-aws-minus-49
  namespace: clusterpool
spec:
  baseDomain: aws.red-chesterfield.com
  imageSetRef:
<<<<<<< HEAD
    name: openshift-v496
=======
    name: openshift-v494
>>>>>>> origin/main
  installConfigSecretTemplateRef:
    name: aws-standard-install-config
  platform:
    aws:
      credentialsSecretRef:
        name: aws-creds
      region: us-east-2
  pullSecretRef:
    name: clusterpool-pull-secret
  size: 2